apiVersion: v1
kind: Service
metadata:
   name: mysql
   labels:
      app: mysql
spec:
   ports:
      - port: 3306
        name: mysql
   clusterIP: None
   selector:
      app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: mysql
   labels:
      app: mysql
spec:
   serviceName: mysql
   replicas: 1
   selector:
      matchLabels:
         app: mysql
   template:
      metadata:
         labels:
            app: mysql
      spec:
         containers:
            - name: mysql
              image: mysql:8.0
              ports:
                 - containerPort: 3306
                   name: mysql
              envFrom:
                 - secretRef:
                      name: findsource-mysql-env
              volumeMounts:
                 - name: mysql-data
                   mountPath: /var/lib/mysql
              livenessProbe:
                 exec:
                    command:
                       - mysqladmin
                       - ping
                       - -h
                       - localhost
                 initialDelaySeconds: 30
                 periodSeconds: 10
              readinessProbe:
                 exec:
                    command:
                       - mysqladmin
                       - ping
                       - -h
                       - localhost
                 initialDelaySeconds: 10
                 periodSeconds: 5
   volumeClaimTemplates:
      - metadata:
           name: mysql-data
        spec:
           accessModes: ["ReadWriteOnce"]
           resources:
              requests:
                 storage: 3Gi
